# Generated by Django 2.2.3 on 2019-07-11 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComissionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_percentage', models.FloatField(verbose_name='Menor Porcentagem')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor Mínimo')),
                ('upper_percentage', models.FloatField(verbose_name='Maior Porcentagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Planos de Comissões',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('address', models.TextField(verbose_name='Endereço')),
                ('phone', models.PositiveIntegerField(verbose_name='Telefone')),
                ('birthday', models.DateField(verbose_name='Data de Nascimento')),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.PositiveIntegerField(verbose_name='CPF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comission_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='televendas.ComissionPlan', verbose_name='Plano de Comissãos')),
            ],
            options={
                'verbose_name_plural': 'Selleres',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', 'Janeiro'), ('2', 'Fevereiro'), ('3', 'Março'), ('4', 'Abril'), ('5', 'Maio'), ('6', 'Junho'), ('7', 'Julho'), ('8', 'Agosto'), ('9', 'Setembro'), ('10', 'Outubro'), ('11', 'Novembro'), ('12', 'Dezembro')], max_length=2, verbose_name='Mês')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor das Vendas')),
                ('comission', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Valor da Comissão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='televendas.Seller')),
            ],
            options={
                'verbose_name_plural': 'Vendas',
                'ordering': ['created_at'],
                'unique_together': {('seller', 'month')},
            },
        ),
    ]
