# Generated by Django 2.2.3 on 2019-07-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComissionPlan',
            fields=[
                ('id', models.AutoField(
                    auto_created=True, primary_key=True,
                    serialize=False, verbose_name='ID')),
                ('lower_percentage', models.FloatField(
                    verbose_name='Menor Porcentagem')),
                ('min_value', models.DecimalField(
                    decimal_places=2, max_digits=8,
                    verbose_name='Valor Mínimo')),
                ('upper_percentage', models.FloatField(
                    verbose_name='Maior Porcentagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Planos de Comissões',
                'ordering': ['created_at'],
            },
        ),
    ]
