# Generated by Django 2.2.3 on 2019-07-30 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='cpf',
            field=models.CharField(help_text='CPF do Vendedor', max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('seller', 'month')},
        ),
        migrations.AlterModelTable(
            name='sale',
            table=None,
        ),
    ]
