# Generated by Django 2.2.3 on 2019-07-24 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televendas', '0002_sale_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='comission_plan',
        ),
        migrations.AlterField(
            model_name='comissionplan',
            name='lower_percentage',
            field=models.FloatField(help_text='The lower comission percentage', verbose_name='Menor Porcentagem'),
        ),
        migrations.AlterField(
            model_name='comissionplan',
            name='min_value',
            field=models.DecimalField(decimal_places=2, help_text='The minimum amount to receive bigger comission', max_digits=8, verbose_name='Valor Mínimo'),
        ),
        migrations.AlterField(
            model_name='comissionplan',
            name='upper_percentage',
            field=models.FloatField(help_text='The bigger comission percentage', verbose_name='Maior Porcentagem'),
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
