# Generated by Django 2.2.3 on 2019-07-29 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('televendas', '0004_sale_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='comission',
        ),
    ]
