# Generated by Django 2.2.3 on 2019-07-29 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('televendas', '0005_remove_sale_comission'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='comission',
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=8),
            preserve_default=False,
        ),
    ]
